services:
  - type: web
    name: my-django-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: "tu-secret-key"
      - key: ALLOWED_HOSTS
        value: "my-django-app.onrender.com"